### PR TITLE
Added in small unit tests

### PR DESCRIPTION
**Pull request by thomastaylor312**
**Changes made:**
- Added Travis config
- Wrote all small unit tests (integration tests will be in a different PR)

**Testing done:**
- All small tests pass

@intelsdi-x/plugin-maintainers

### CODE REVIEW

**Comment by IzabellaRaulin** [comment]
It will be helpful if the results of travis tests are available for this pull request. 

The `GetMetricTypes` and `GetConfigPolicy` are covered, what is about `CollectMetrics()`? Is there any plan to test it?

Others that these above looks good to me.

**Comment by thomastaylor312** [comment]
@IzabellaRaulin The travis results won't show up until this is merged to master. I already tried 😦 . But `CollectMetrics` will be an integration test that I will write as soon as I figure out the best way to spin up a test ScaleIO cluster with Docker

**Comment by thomastaylor312** [comment]
@IzabellaRaulin So is this good to go?

**Comment by candysmurf** [comment]
LGTM

**Pull request merged**
